name: Ruff Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ruff-action
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: format
          # Uncomment and customize if needed:
          # src: .
          # version: latest
          # version-file: pyproject.toml
          # checksum: ""
          # github-token: ${{ github.token }}
